export { Profile } from './profile'
export { PrivateProfile } from './private-profile'
export { PublicProfile } from './public-profile'
export { AboutUs } from './about-us'
export { Privacy } from './privacy'
export { ChangePhone } from './change-phone'
